repo: "css-validation-fixes"
canvasCourse: "467502"
canvasAssignment: "4178294"

naming: true
commits: 2

html:
  - path: "index.html"
    valid: true
    bestPractices: true

css:
  - path: "css/main.css"
    valid: true
    bestPractices: true
